[versions]
minecraft            = "1.21.4"
fabric-loader        = "0.16.9"
parchment            = "1.21:2024.11.10"
fabric-api           = "0.110.5+1.21.4"
fabric-kotlin        = "1.13.0+kotlin.2.1.0"
map-canvas           = "0.5.0+1.21.3"
arcade               = "0.4.0-alpha.8+1.21.4"
server-replay        = "1.2.6+1.21.4"
casual-database      = "0.2.0"

# Plugins
fabric-loom = "1.9-SNAPSHOT"

[libraries]
minecraft       = { module = "com.mojang:minecraft"                         , version.ref = "minecraft" }
fabric-loader   = { module = "net.fabricmc:fabric-loader"                   , version.ref = "fabric-loader" }
fabric-api      = { module = "net.fabricmc.fabric-api:fabric-api"           , version.ref = "fabric-api" }
fabric-kotlin   = { module = "net.fabricmc:fabric-language-kotlin"          , version.ref = "fabric-kotlin" }
map-canvas      = { module = "eu.pb4:map-canvas-api"                        , version.ref = "map-canvas" }
arcade          = { module = "net.casual-championships:arcade"              , version.ref = "arcade" }
arcade-datagen  = { module = "net.casual-championships:arcade-datagen"      , version.ref = "arcade" }
casual-database = { module = "net.casual-championships:casual-database-core", version.ref = "casual-database" }
server-replay   = { module = "me.senseiwells:server-replay"                 , version.ref = "server-replay" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }